// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtT5OE8W26movTFu_lLLCKPu0lZTXPFSI',
    appId: '1:407651784707:web:8802e5f03230c8edc15636',
    messagingSenderId: '407651784707',
    projectId: 'app-reading-book-b86b2',
    authDomain: 'app-reading-book-b86b2.firebaseapp.com',
    storageBucket: 'app-reading-book-b86b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREDScF_ShyOybaqurFe0L6jGagjdU1vo',
    appId: '1:407651784707:android:591d3e19d98aa49cc15636',
    messagingSenderId: '407651784707',
    projectId: 'app-reading-book-b86b2',
    storageBucket: 'app-reading-book-b86b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmVVDMZsNCD1yVc1eJ1Vo6T4sn6Xe8Ppk',
    appId: '1:407651784707:ios:ffb1ea394af7264ec15636',
    messagingSenderId: '407651784707',
    projectId: 'app-reading-book-b86b2',
    storageBucket: 'app-reading-book-b86b2.appspot.com',
    iosBundleId: 'com.uzair657.oms',
  );
}
